### ISSUE TITLE
Specifying a git repository as an dependency in `dub.json`  does not seem to be supported

### ISSUE THREAD

**Issue by HenkKalkwater** [lionello/dub2nix#20]
Specifying a git repository as an dependency in `dub.json` instead of a version number does not seem to be supported. Example `dub.json`:
```json
{
	// The regular fields…
	"dependencies": {
		"bar": {
			"repository": "git+https://github.com/foo/bar.git",
			"version": "<git revision>"
		},

}
```

Example `dub.selections.json`:
```json
{
	"fileVersion": 1,
	"versions": {
		"bar": {"version":"<git revision>","repository":"git+https://github.com/foo/bar.git"},
	}
}
```

Error:
```bash
$ dub2nix save
Error: Expected '"' to start string.
```

**Comment by lionello** [comment]
Thanks for the report. I've started looking into this, but unfortunately it's not a quick fix. The JSON parser from Dub doesn't support a map value that can be either a string or an object.

**Comment by lionello** [comment]
I think I figured it out. @HenkKalkwater could you test latest master? Commit a871e5494dc22eb203cf7c39663f7d3d1aa34d
